module.exports = {
  mobiles: [
    {
      id: 1,
      details_id: 101,
      name: "New Apple iPhone 12 Mini - Blue",
      mrp: 74900,
      price: 71900,
      yousave: 3000,
      image:
        "https://images-na.ssl-images-amazon.com/images/I/71sNNCTfMuL._SX679_.jpg",
      ram: 8,
      internal_memory: 128,
      brand: "Apple",
      colour: "Blue",
      discount: 4,
    },
    {
      id: 2,
      details_id: 101,
      name: "New Apple iPhone 12 Mini - Black",
      mrp: 74900,
      price: 71900,
      yousave: 3000,
      image: "https://m.media-amazon.com/images/I/71uuDYxn3XL._SX466_.jpg",
      ram: 8,
      internal_memory: 128,
      brand: "Apple",
      colour: "Black",
      discount: 4,
    },
    {
      id: 3,
      details_id: 101,
      name: "New Apple iPhone 12 Mini - Blue",
      mrp: null,
      price: 84900,
      yousave: null,
      image:
        "https://images-na.ssl-images-amazon.com/images/I/71sNNCTfMuL._SX679_.jpg",
      ram: 16,
      internal_memory: 256,
      brand: "Apple",
      colour: "Blue",
      discount: null,
    },
    {
      id: 4,
      details_id: 101,
      name: "New Apple iPhone 12 Mini - Black",
      mrp: null,
      price: 84900,
      yousave: null,
      image: "https://m.media-amazon.com/images/I/71uuDYxn3XL._SX466_.jpg",
      ram: 16,
      internal_memory: 256,
      brand: "Apple",
      colour: "Black",
      discount: null,
    },
    {
      id: 5,
      details_id: 102,
      name: "New Apple iPhone 11 - Red",
      mrp: null,
      price: 59900,
      yousave: null,
      image: "https://m.media-amazon.com/images/I/71hh7cpWadL._SX466_.jpg",
      ram: 8,
      internal_memory: 128,
      brand: "Apple",
      colour: "Red",
      discount: null,
    },
    {
      id: 6,
      details_id: 102,
      name: "New Apple iPhone 11 - Black",
      mrp: null,
      price: 59900,
      yousave: null,
      image:
        "https://images-na.ssl-images-amazon.com/images/I/71i2XhHU3pL._SX466_.jpg",
      ram: 8,
      internal_memory: 128,
      brand: "Apple",
      colour: "Black",
      discount: null,
    },
    {
      id: 7,
      details_id: 102,
      name: "New Apple iPhone 11 - Red",
      mrp: null,
      price: 69900,
      yousave: null,
      image: "https://m.media-amazon.com/images/I/71hh7cpWadL._SX466_.jpg",
      ram: 16,
      internal_memory: 256,
      brand: "Apple",
      colour: "Black",
      discount: null,
    },
    {
      id: 8,
      details_id: 102,
      name: "New Apple iPhone 11 - Black",
      mrp: null,
      price: 69900,
      yousave: null,
      image:
        "https://images-na.ssl-images-amazon.com/images/I/71i2XhHU3pL._SX466_.jpg",
      ram: 16,
      internal_memory: 256,
      brand: "Apple",
      colour: "Black",
      discount: null,
    },
    {
      id: 9,
      details_id: 103,
      name: "Redmi 9A | 2GHz Octa-core Helio G25 Processor - Midnight Black",
      mrp: 8499,
      price: 6799,
      yousave: 1700,
      image: "https://m.media-amazon.com/images/I/71hDPUM7VPL._SX569_.jpg",
      ram: 2,
      internal_memory: 32,
      brand: "Redmi",
      colour: "Black",
      discount: 20,
    },
    {
      id: 10,
      details_id: 103,
      name: "Redmi 9A | 2GHz Octa-core Helio G25 Processor - Midnight Green",
      mrp: 8499,
      price: 6799,
      yousave: 1700,
      image: "https://m.media-amazon.com/images/I/71hDPUM7VPL._SX569_.jpg",
      ram: 2,
      internal_memory: 32,
      brand: "Redmi",
      colour: "Green",
      discount: 20,
    },
    {
      id: 11,
      details_id: 103,
      name: "Redmi 9A | 2GHz Octa-core Helio G25 Processor - Midnight Black",
      mrp: 9499,
      price: 7500,
      yousave: 1999,
      image: "https://m.media-amazon.com/images/I/71hDPUM7VPL._SX569_.jpg",
      ram: 3,
      internal_memory: 32,
      brand: "Redmi",
      colour: "Black",
      discount: 21,
    },
    {
      id: 12,
      details_id: 103,
      name: "Redmi 9A | 2GHz Octa-core Helio G25 Processor - Midnight Green",
      mrp: 9499,
      price: 7500,
      yousave: 1999,
      image: "https://m.media-amazon.com/images/I/71hDPUM7VPL._SX569_.jpg",
      ram: 3,
      internal_memory: 32,
      brand: "Redmi",
      colour: "Green",
      discount: 21,
    },
    {
      id: 13,
      details_id: 104,
      name: "Redmi 9 - Sky Blue",
      mrp: 10999,
      price: 9999,
      yousave: 1000,
      image: "https://m.media-amazon.com/images/I/71A9Vo1BatL._SX425_.jpg",
      ram: 4,
      internal_memory: 128,
      brand: "Redmi",
      colour: "Blue",
      discount: 9,
    },
    {
      id: 14,
      details_id: 104,
      name: "Redmi 9 - Sporty Orange",
      mrp: 10999,
      price: 9999,
      yousave: 1000,
      image: "https://m.media-amazon.com/images/I/71A9Vo1BatL._SX425_.jpg",
      ram: 4,
      internal_memory: 128,
      brand: "Redmi",
      colour: "Orange",
      discount: 9,
    },
    {
      id: 15,
      details_id: 104,
      name: "Redmi 9 - Sky Blue",
      mrp: 10999,
      price: 8799,
      yousave: 2200,
      image: "https://m.media-amazon.com/images/I/71A9Vo1BatL._SX425_.jpg",
      ram: 4,
      internal_memory: 64,
      brand: "Redmi",
      colour: "Blue",
      discount: 20,
    },
    {
      id: 16,
      details_id: 104,
      name: "Redmi 9 - Sporty Orange",
      mrp: 10999,
      price: 8799,
      yousave: 2200,
      image: "https://m.media-amazon.com/images/I/71A9Vo1BatL._SX425_.jpg",
      ram: 4,
      internal_memory: 64,
      brand: "Redmi",
      colour: "Orange",
      discount: 20,
    },
    {
      id: 17,
      details_id: 105,
      name: "Samsung Galaxy M21 - Black",
      mrp: null,
      price: 13999,
      yousave: null,
      image: "https://m.media-amazon.com/images/I/71QLvGIAq5L._SY606_.jpg",
      ram: 4,
      internal_memory: 64,
      brand: "Samsung",
      colour: "Black",
      discount: null,
    },
    {
      id: 18,
      details_id: 105,
      name: "Samsung Galaxy M21 - Blue",
      mrp: null,
      price: 13999,
      yousave: null,
      image:
        "https://images-na.ssl-images-amazon.com/images/I/71dujTTJDZL._SY445_.jpg",
      ram: 4,
      internal_memory: 64,
      brand: "Samsung",
      colour: "Blue",
      discount: null,
    },
    {
      id: 19,
      details_id: 105,
      name: "Samsung Galaxy M21 - Black",
      mrp: 17199,
      price: 15999,
      yousave: 1200,
      image: "https://m.media-amazon.com/images/I/71QLvGIAq5L._SY606_.jpg",
      ram: 6,
      internal_memory: 128,
      brand: "Samsung",
      colour: "Black",
      discount: 7,
    },
    {
      id: 20,
      details_id: 105,
      name: "Samsung Galaxy M21 - Blue",
      mrp: 17199,
      price: 15999,
      yousave: 1200,
      image:
        "https://images-na.ssl-images-amazon.com/images/I/71dujTTJDZL._SY445_.jpg",
      ram: 6,
      internal_memory: 128,
      brand: "Samsung",
      colour: "Blue",
      discount: 7,
    },
  ],
  price: ["Under ₹1000", "₹5000 - ₹10000", "₹10000 - ₹20000", "Over ₹20000"],
  brands: ["Apple", "Redmi", "Samsung"],
  internal_memory: ["8 GB", "32 GB", "64 GB", "128 GB"],
  ram: ["8GB & above", "6GB", "4GB", "3GB"],
  colour: ["Black", "Blue", "Orange"],
  discount: ["0 - 10%", "10% - 20%", "30% - 40%"],
};
